Feature/apply markdown
kalgory/Web_Kalgory pull request #25
Opened 2021-02-06 13:54 UTC by dmin0211

## Feature

apply-markdown: Post들의 body에 stackoverflow를 오마주하여 마크다운 문법을 적용. community 토글버튼 추가

## Changes

- package.json - marked, sanitize-html package 추가
- main.js - package install
- PostsDataIterator.vue - 필요없는 console log 삭제
- BaseCommunity - 토글 버튼기능을 포함한 community toolbar추가
- CommunityToolbar - community내에서 토글 버튼 기능을 하는 버튼을 포함한 컴포넌트. disabled로 현재 route에 해당하는 버튼은 비활성화
- CreatForm.vue - body 입력에 marked적용하여 markdown 문법 적용 및 sanitize-html, v-html으로 preview 구현
- DataCard.vue - Posts에서 보여지는 카드로 해당 post body역시 markdown 적용 및 정규식을 활용하여 끝맺음</> 혹은 줄바꿈 <br/> 태그들을 기준으로 body자르기 추기

2021-02-07 03:22 UTC, hyunmindev reviewed
**함 고치보자**

2021-02-07 03:22 UTC, hyunmindev commented on src/views/community/CommunityToolbar.vue
> +      :disabled="this.$route.name.indexOf('information')!==-1"
굳이 disable 할 필요 있나?

2021-02-07 03:22 UTC, hyunmindev commented on src/views/community/CommunityToolbar.vue
> +      :disabled="this.$route.name.indexOf('default')!==-1"
name 이 string으로 return 되는걸로 알고있는데 indexOf 해서 default를 찾는 단건 이 name이 default인지 아닌지 판단하는거?
그러면
```
this.$route.name === 'default'
```
이렇게 해도 되는거 아니냐?

2021-02-07 03:22 UTC, hyunmindev commented on src/views/community/CommunityToolbar.vue
> +      :disabled="this.$route.name.indexOf('question')!==-1"
내생각에 disable 보단
vuetify 도큐먼트 보면 v-btn props로 active class 로 현재 어떤 라우트에 있다는걸 표현하는게 더 나을듯

2021-02-07 03:22 UTC, hyunmindev commented on src/components/community/question/post/create/CreateForm.vue
>            console.error(error);
이 부분 console error -> toated notification 대체 바람

2021-02-07 03:22 UTC, hyunmindev commented on src/components/community/question/post/create/CreateForm.vue
> +    markdownString: '',
얘는 사용처가 어디냐?

2021-02-07 03:22 UTC, hyunmindev commented on src/components/community/question/post/create/CreateForm.vue
>        header: '',
얘네들 object로 할 필요 있나?

2021-02-07 03:22 UTC, hyunmindev commented on src/components/community/question/post/create/CreateForm.vue
> +    postBody() {
가공된 post.body 임에도 postBody라는 변수명은 불명확함
markedBody 이런식으로 가야할듯

2021-02-07 03:22 UTC, hyunmindev commented on src/components/community/question/posts/data/DataCard.vue
> +      return markedHtml;
알고리즘적인 영역 같은데 깊게 고민해봐야할듯
정규표현식으로 했네

2021-02-07 03:22 UTC, hyunmindev commented on src/views/BaseCommunity.vue
> +import CommunityToolbar from '@/views/community/CommunityToolbar.vue';
community toolbar는 route로 보여지는 뷰가 아니어서 views 말고 components가 더 적절한듯

2021-02-07 03:37 UTC, dmin0211 commented on src/views/community/CommunityToolbar.vue
> +      :disabled="this.$route.name.indexOf('information')!==-1"
나도 어제 자기전에 그생각함 ㅅㄱ

2021-02-07 03:38 UTC, hyunmindev commented on src/views/community/CommunityToolbar.vue
> +      :disabled="this.$route.name.indexOf('information')!==-1"
자기전에 그딴생각하면 코딩하는 꿈꾼다

2021-02-07 03:38 UTC, dmin0211 commented on src/views/community/CommunityToolbar.vue
> +      :disabled="this.$route.name.indexOf('default')!==-1"
Default는 default밖에 없어서 상관없지만 다른거랑 맞추기위해서 저렇게 쓴거임

2021-02-07 03:40 UTC, hyunmindev commented on src/views/community/CommunityToolbar.vue
> +      :disabled="this.$route.name.indexOf('default')!==-1"
다른것들은 name string 중에 question 이 있는걸 판단하려고?

2021-02-07 03:40 UTC, hyunmindev commented on src/views/community/CommunityToolbar.vue
> +      :disabled="this.$route.name.indexOf('default')!==-1"
그러면 https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/String/includes
이거 참고해보셈

2021-02-07 03:44 UTC, dmin0211 commented on src/components/community/question/posts/data/DataCard.vue
> +      return markedHtml;
구분자 2개쓰려고 정규식으로 했고 html 줄을 판단하는게 내가 적어둔 방식으로 할지 더생각할게 있는지 고민해야될듯

2021-02-07 03:45 UTC, hyunmindev commented on src/components/community/question/posts/data/DataCard.vue
> +      return markedHtml;
나도 여유되면 괜찮은 방식 한번 생각해봄

2021-02-07 06:01 UTC, dmin0211 commented on src/components/community/question/post/create/CreateForm.vue
>        header: '',
지금이야 해더 바디 밖에 없지만 나중에 사용자 아이디랑 추가적인 부분도 들어갈 수 있고 createPost자체에 파라미터로 오브젝트가 넘어감

2021-02-07 06:03 UTC, dmin0211 commented on src/components/community/question/posts/data/DataCard.vue
> +      return markedHtml;
이부분이 알고리즘적인 영역이 들어가는 부분이 모르겠는데 어디보고 말한거임?

2021-02-07 06:03 UTC, dmin0211 commented on src/components/community/question/post/create/CreateForm.vue
> +    postBody() {
ㅇㅇ맞는것같아서 고쳤다

2021-02-07 06:05 UTC, hyunmindev commented on src/components/community/question/post/create/CreateForm.vue
> +    postBody() {
고친건 resolve 버튼 누르셈

2021-02-07 06:05 UTC, dmin0211 commented on src/views/community/CommunityToolbar.vue
> +      :disabled="this.$route.name.indexOf('information')!==-1"
버튼 on이벤트로 해당 라우터조사하고 push하는 방향으로 하면 disable도 필요없고 너말대로 active로 하면 깔끔하긴 할듯 그리고 그냥 버튼 to 옵션으로 해당 라우터에 존재하면 버튼이 활성화 되어있는데 그렇게 두는건 어떻게 생각함?

2021-02-07 06:06 UTC, hyunmindev commented on src/components/community/question/posts/data/DataCard.vue
> +      return markedHtml;
string을 marked해서 자르는 로직구현이 알고리즘 영역이라고 말한거
근데 이부분 관련해서 좋은 생각남

2021-02-07 06:08 UTC, dmin0211 commented on src/views/BaseCommunity.vue
> +import CommunityToolbar from '@/views/community/CommunityToolbar.vue';
views에서 쓰지말고 컴포넌트에서 쓰라는 말인가? 근데 이 버튼들은 모든 커뮤니티 사이트들 상단에 위치하는거라 오히려 최상단 view에 넣는게 좋지 않을까

2021-02-07 06:08 UTC, hyunmindev commented on src/views/community/CommunityToolbar.vue
> +      :disabled="this.$route.name.indexOf('information')!==-1"
디폴트로 active class가 적용돼있는거여서 활성화가 되는거인듯
나중에 ui 다룰때 acitve class 커스터마이징 하는걸로 하고 지금은 디폴트로 두자

2021-02-07 06:10 UTC, hyunmindev commented on src/views/BaseCommunity.vue
> +import CommunityToolbar from '@/views/community/CommunityToolbar.vue';
views 는 말그대로 route랑 1대1대응이 돼야함
모든 커뮤니티 페이지에서 상단에 위치하는건 맞는데
그건 toolbar를 컴포넌트에 두고 쓰는건 views 에서 쓰는게 맞지않나

2021-02-07 13:48 UTC, hyunmindev requested changes

2021-02-07 13:48 UTC, hyunmindev commented on src/components/community/CommunityToolbar.vue
> +
한줄 띄운거 머임?

2021-02-08 12:40 UTC, dmin0211 commented on src/components/community/question/posts/data/DataCard.vue
>        }
here

2021-02-08 14:48 UTC, hyunmindev approved these changes
수고

2021-02-08 14:48 UTC, merged