Feature/post router guard
kalgory/Web_Kalgory pull request #37
Opened 2021-02-26 12:57 UTC by dmin0211

## Description

존재하지 않는 ID값의 post에 접근 시 페이지를 찾을 수 없다는 메세지 출력, 포스트 관련 구조 변경

## Changes

- AppBar.vue - rebase QuestionContainer.vue - 질문에 대한 Post, Answer table을 담고 있는 container생성
- AnswerSimpleTable.vue - 해당 포스트에 answer collention에 접근해서 데이터를 read한 후에 answers에 담고 simple table에서 data - card component로 넘겨준다.
- Question/answer/data/DataCard.vue - props로 받은 answer를 sanitizeHTML과 marked를 거친 후 v-html로 보여준다.
- Question/post/read/ReadCard.vue - 테두리를 없애고 card안에 내용으로 데이터를 읽으면 해당 데이터를 띄워주고 데이터가 없다면 page not find를 띄워준다.
- Firebase/firestore/community/index.js - Answer Collection querySnapshot을 read하는 함수 추가
- QuestionPost.vue - container을 제거하고 post의 데이터를 관리하는 QuestionContainer을 추가 

2021-02-26 13:34 UTC, hyunmindev requested changes

2021-02-26 13:34 UTC, hyunmindev commented on src/components/community/question/QuestionContainer.vue
> +      <answer-simple-table />
v-col 없이 바로 담는건 어떤의미가 있는거냐

2021-02-26 13:34 UTC, hyunmindev commented on src/plugins/firebase/firestore/community/index.js
> +}
readPost 함수로 readAnswer readQuestion 둘다 재사용할수있는거 아니냐?
Community Information 에서도 마찬가지로 readPost 사용할 수 있는거고

2021-02-26 13:34 UTC, hyunmindev commented on src/components/community/question/answer/AnswerSimpleTable.vue
> +    itemCountPerPage: 0,
이 컴포넌트에서 이 아이의 역할은 무엇인고?

2021-02-26 13:34 UTC, hyunmindev commented on src/components/community/question/answer/data/DataCard.vue
> +    <v-card-text>{{ answer.createdAt }}</v-card-text>
이건 개발용 코드제?

2021-02-26 13:34 UTC, hyunmindev commented on src/components/community/question/answer/data/DataCard.vue
> +</script>
이 데이터 카드도 Question Post 의 데이터카드랑 재 사용이 가능한거 아니냐
question 이랑 answer 랑의 차이점은 header 가 있냐 없냐의 차이인데 그건 props 등으로 처리 가능한거고

2021-02-26 13:34 UTC, hyunmindev commented on src/components/community/question/post/read/ReadCard.vue
> +    </div>
이 부분이 ReadCard 컴포넌트에 있으면 아이디에 해당하는 포스트가 없을 시 Answer 은 어떻게 되노
내생각에 이부분은 이 컴포넌트의 상위 Container 에서 해줘야하는거 같은데

2021-02-26 13:34 UTC, hyunmindev commented on src/components/community/question/post/read/ReadCard.vue
> +        this.isPostExist = false;
포스트가 존재하지 않을 시에만 에러를 뱉는게 아니기 때문에 추가적인 조건이 필요할꺼같다

2021-02-26 14:33 UTC, dmin0211 commented on src/components/community/question/post/read/ReadCard.vue
> +    </div>
어차피 포스트가 없으면 answer도 못 읽어서 일단 안에서 해둔거였는데

2021-02-26 14:33 UTC, dmin0211 commented on src/components/community/question/answer/data/DataCard.vue
> +    <v-card-text>{{ answer.createdAt }}</v-card-text>
?아님

2021-02-26 14:33 UTC, dmin0211 commented on src/components/community/question/answer/AnswerSimpleTable.vue
> +    itemCountPerPage: 0,
ㄷㅊ

2021-02-26 14:35 UTC, dmin0211 commented on src/plugins/firebase/firestore/community/index.js
> +}
아 reference만 다르게 하면 되겠네

2021-02-26 14:35 UTC, dmin0211 commented on src/components/community/question/QuestionContainer.vue
> +      <answer-simple-table />
ㄷㅊ

2021-02-26 14:35 UTC, hyunmindev commented on src/components/community/question/answer/AnswerSimpleTable.vue
> +    itemCountPerPage: 0,
어디 사용된거임?

2021-02-26 14:36 UTC, hyunmindev commented on src/components/community/question/answer/data/DataCard.vue
> +    <v-card-text>{{ answer.createdAt }}</v-card-text>
카드 텍스트에 created at을 유저한테 왜보여줌?

2021-02-26 14:36 UTC, dmin0211 commented on src/components/community/question/answer/data/DataCard.vue
> +    <v-card-text>{{ answer.createdAt }}</v-card-text>
나중에 다듬어서 보여줘야지 일단 자리 정해둔거

2021-02-26 14:37 UTC, hyunmindev commented on src/components/community/question/answer/data/DataCard.vue
> +    <v-card-text>{{ answer.createdAt }}</v-card-text>
그럼 개발용 코드 아니냐?

2021-02-26 16:17 UTC, dmin0211 commented on src/components/community/question/post/read/ReadCard.vue
> +        this.isPostExist = false;
ㅇㅇ post id유무로 판단하는걸로 바꿔뒀어

2021-02-26 16:18 UTC, dmin0211 commented on src/components/community/question/answer/data/DataCard.vue
> +</script>
card랑 마찬가지로 table도 재사용 많이될 것 같아서 common에 card, simple table둘 다 재사용 되게 처리해뒀음

2021-02-26 16:18 UTC, dmin0211 commented on src/components/community/question/answer/AnswerSimpleTable.vue
> +    itemCountPerPage: 0,
삭제

2021-02-26 16:19 UTC, dmin0211 commented on src/plugins/firebase/firestore/community/index.js
> +}
이것도 getreference중에 getSubCollectionReference만들고 readPosts재사용하는 식으로 바꿨다

2021-02-26 16:20 UTC, dmin0211 commented on src/plugins/firebase/firestore/community/index.js
> +}
재사용하는 props에서 상위컬랙션의 reference랑 targetCollection받아서 상위 컬랙션 있으면 해당 reference에 targetCollection을 read하고 상위컬랙션이 없으면 그냥 targetCollection을 read하는 식으로

2021-02-26 16:20 UTC, dmin0211 commented on src/components/community/question/QuestionContainer.vue
> +      <answer-simple-table />
삭제

2021-02-26 16:23 UTC, dmin0211 commented on src/components/community/question/post/read/ReadCard.vue
> +    </div>
이거는 firestore get할 때 해당 id값이 없으면 error도 아니라 그냥 넘어가서 answer이 안띄워지는거라 그냥 둔거임 상위 container에서 이벤트 받고 처리하는거랑 차이가 없어서

2021-02-27 02:39 UTC, hyunmindev commented on src/components/community/common/CommonSimpleTable.vue
> +        this.isLoading = true;
이부분에서 this.readPost() 를 호출하고

2021-02-27 02:39 UTC, hyunmindev commented on src/components/community/common/CommonSimpleTable.vue
> +      readPosts(this.getReference, this.readNumber, this.lastSnapshot)
이 함수에서 this.isLoading = true; 로 가는게

2021-02-27 02:39 UTC, hyunmindev commented on src/components/community/common/CommonSimpleTable.vue
> +      if (isLoading) this.readPosts();
이 흐름보다 낫지 않나

2021-02-27 02:39 UTC, hyunmindev commented on src/components/community/common/CommonSimpleTable.vue
> +<template>
이 파일 폴더 경로를 common/posts/PostsSimpleTable.vue  이게 안낫겠나

2021-02-27 02:39 UTC, hyunmindev commented on src/components/community/common/CommonSimpleTable.vue
> +    items: [],
변수명 posts 하는건

2021-02-27 02:39 UTC, hyunmindev commented on src/components/community/common/CommonSimpleTable.vue
> +    completeRead: false,
변수명 다시 정해야할듯

2021-02-27 02:39 UTC, hyunmindev commented on src/components/community/common/CommonSimpleTable.vue
> +    itemCountPerPage: 3,
임마도 item 보단 post 가 나을거같기도

2021-02-27 02:39 UTC, hyunmindev commented on src/components/community/common/CommonSimpleTable.vue
> +          this.isLoading = false;
catch 에서 this.isLoading = true 해주는 부분이랑 then 에서 this.isLoading 해주는 부분이랑 빼서
```
.final(()=> {
  this.isLoading = false; 
})
```
이런식으로 중복제거

2021-02-27 02:39 UTC, hyunmindev commented on src/components/community/question/post/read/ReadCard.vue
> +        }
아마 에러 코드중에 존재하는 도큐먼트가 없다는 코드가 있을껀데 그거로 판단하는게 더 간단하지 않나

2021-02-27 02:39 UTC, hyunmindev commented on src/components/community/common/CommonSimpleTable.vue
> +    itemCountPerPage: 3,
글고 개수를 나타내는 변수 number 랑 count 일관성 유지바람

2021-02-27 02:39 UTC, hyunmindev commented on src/components/community/common/data/DataCard.vue
> +            </v-icon>
{{ expandButtonIcon }}
해서 computed 로 아이콘 이름 return 해주는것도 좋을꺼같은데

2021-02-27 02:39 UTC, hyunmindev commented on src/components/community/question/QuestionContainer.vue
> +      />
답변을 common simple table로 하면 answer 에도 expand 할수잇는게 생기는건가 그게 필요한가

2021-02-27 02:40 UTC, hyunmindev commented on src/components/community/common/CommonSimpleTable.vue
> +    getReference() {
컴퓨티드 이름이 메소드이름같음

2021-02-27 02:43 UTC, hyunmindev commented
common simple table 에 저 레퍼런트슬 컴포넌트 안에서 계산하는것보단 난 저 컴포넌트를 사용하는쪽에서 레퍼런스르 다 꼐산해서 던져주는게 더 자유도가 높고 재사용성 높다고 생각하는데

2021-02-27 05:16 UTC, dmin0211 commented on src/components/community/common/CommonSimpleTable.vue
> +    items: [],
이게 post만이 아니라 answer comment도 테이블로 담을려고 해서 post로 분류하는건 어색해서 common으로 빼고 items로 했던건데 어떻게 생각함?

2021-02-27 05:17 UTC, dmin0211 commented on src/components/community/common/CommonSimpleTable.vue
> +<template>
이 역시 post로 분류하기보단 comments, answers도 받을거라서 common으로 빼뒀었어

2021-02-27 05:18 UTC, dmin0211 commented on src/components/community/common/CommonSimpleTable.vue
> +    itemCountPerPage: 3,
아 저 변수 지워야됨 searchText랑

2021-02-27 05:28 UTC, dmin0211 commented on src/components/community/question/QuestionContainer.vue
> +      />
data card보면
```
<v-card-actions v-if="!isBodyRenderingHtml">
      <v-row>
        <v-col align="end">
          <v-btn
            icon
            @click="isExpand=!isExpand"
          >
            <v-icon v-if="isExpand">
              mdi-chevron-up
            </v-icon>
            <v-icon v-if="!isExpand">
              mdi-chevron-down
            </v-icon>
          </v-btn>
        </v-col>
      </v-row>
    </v-card-actions>
```
이렇게 props으로 랜더링이 필요한 body인지 받고 랜더링이 필요하지 않다는거 자체가 posts에서 미리보기하는 datacard이니까 그걸로 판단해서 가려줌

2021-02-27 05:36 UTC, dmin0211 commented
테이블을 view에서도 사용하는데 views에서 reference계산하는게 맞는지 몰라서 일단 테이블에 넣어뒀었어

2021-02-27 07:09 UTC, hyunmindev requested changes

2021-02-27 07:09 UTC, hyunmindev commented on src/components/community/common/CommonSimpleTable.vue
> +    items: [],
answer table 이랑 comment 까지 한 컴포넌트를 재사용하기엔 효율성이 너무 떨어지지 않나?
내가 원하는 재사용 수준은 Information Posts Question Posts 이렇게 두개 묶고
comment 랑 answer 은 따로 처리 해주는게 나중에 다른 카테고리의 게시판이 추가될때 확장 효율이 좋을듯한데

2021-02-27 07:09 UTC, hyunmindev commented on src/components/community/question/QuestionContainer.vue
> +      />
이 부분도 위 커멘트와 마찬가지로 answer post 테이블이랑 question post 테이블을 재사용 컴포넌트로 같이 쓰기보단
레벨이 비슷한 question posts 랑 information posts를

2021-02-28 11:26 UTC, hyunmindev requested changes

2021-02-28 11:26 UTC, hyunmindev commented on src/components/community/posts/PostsSimpleTable.vue
> +    },
컬렉션 네임으로 받기로했나?

2021-02-28 11:26 UTC, hyunmindev commented on src/plugins/firebase/firestore/community/index.js
> +
이 함수는 이 파일에 필요한가?

2021-02-28 11:26 UTC, hyunmindev commented on src/plugins/firebase/firestore/community/index.js
> +        }
에러 클래스 인스턴스를 reject에 넘겨주는게 더깔끔할듯

2021-02-28 11:26 UTC, hyunmindev commented on src/plugins/firebase/firestore/community/index.js
> +        }
도큐먼트스냅샷이 없으면 자동으로 에러를 throw 하는게 아니라 수동으로 해줘야하는거냐?

2021-02-28 11:26 UTC, hyunmindev commented on src/plugins/firebase/firestore/community/index.js
> +export function readPosts(reference, count = Number, snapshot = {}) {
여기 이 Number는 어떤역할을 하는거?

2021-02-28 11:26 UTC, hyunmindev commented on src/components/community/post/read/ReadCard.vue
> +      @click="$router.push({path:`/community/question/${post.id}`})"
router push 이거 객체말고 그냥 path 스트링 적으면 안되나?

2021-02-28 11:26 UTC, hyunmindev commented on src/components/community/post/PostContainer.vue
> +      return getSubCollectionReference(getQuestionCommunityReference(), this.$route.params.id, 'ANSWER');
이거 함수 모듈로 하기보단 그냥 여기서 해주면될꺼같기도 한데

2021-02-28 11:26 UTC, hyunmindev commented on src/components/community/post/PostContainer.vue
> +      return getSubCollectionReference(getQuestionCommunityReference(), this.$route.params.id, 'ANSWER');
함수이름은 getAnswerPostsCollectionReference

2021-03-02 09:31 UTC, hyunmindev approved these changes

2021-03-02 09:31 UTC, merged